/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import classes.Contato;
import classes.Email;
import classes.Fone;
import classes.TipoEmail;
import classes.TipoFone;
import classes.Util;
import controle.Consultas;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DIEGOHEYY
 */
public class TelaCadastro extends javax.swing.JFrame {

    private Contato contatoAtual;

    public TelaCadastro() {
        initComponents();
        preparaCombo();
        bt_gravAlt.setVisible(false);
        bt_cancelAlt.setVisible(false);
        bt_gravNovo.setVisible(true);
        bt_cancelNovo.setVisible(true);
    }

    public TelaCadastro(Contato c) {
        contatoAtual = c;
        initComponents();
        preparaCombo();
        tex_nome.setText(c.getNome());
        tex_sobrenome.setText(c.getSobrenome());
        bt_gravAlt.setVisible(true);
        bt_cancelAlt.setVisible(true);
        bt_gravNovo.setVisible(false);
        bt_cancelNovo.setVisible(false);
        carregaInfo(contatoAtual);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void carregaInfo(Contato c) {
        List<Email> em = c.getEmails();
        DefaultTableModel tab = (DefaultTableModel) tab_email.getModel();
        tab.setNumRows(0);
        for (Email com : em) {
            tab.addRow(com.infoBasico());
        }

        List<Fone> fo = c.getFones();
        DefaultTableModel tab1 = (DefaultTableModel) tab_fone.getModel();
        tab1.setNumRows(0);
        for (Fone co : fo) {
            tab1.addRow(co.infoBasico());
        }
    }

    private void preparaCombo() {
        String[] tipoe = Consultas.vetTipoEmail();
        for (String desce : tipoe) {
            box_email.addItem(desce);
        }
        String[] tipof = Consultas.vetTipoFone();
        for (String descf : tipof) {
            box_fone.addItem(descf);
        }
    }

    private List<Fone> novosFones() {
        DefaultTableModel tab = (DefaultTableModel) tab_fone.getModel();

        List<Fone> lista = new ArrayList<>(0);

        for (int linha = 0; linha < tab.getRowCount(); linha++) {
            TipoFone tipo = new TipoFone(Integer.parseInt((String) tab.getValueAt(linha, 2)), (String) tab.getValueAt(linha, 1));

            lista.add(new Fone((String) tab.getValueAt(linha, 0), tipo));
        }

        return lista;
    }

    private List<Email> novosEmails() {
        DefaultTableModel tab = (DefaultTableModel) tab_email.getModel();

        List<Email> lista = new ArrayList<>(0);

        for (int linha = 0; linha < tab.getRowCount(); linha++) {
            TipoEmail tipo = new TipoEmail(Integer.parseInt((String) tab.getValueAt(linha, 2)), (String) tab.getValueAt(linha, 1));
            lista.add(new Email((String) tab.getValueAt(linha, 0), tipo));
        }

        return lista;
    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tab_email = new javax.swing.JTable();
        text_email = new javax.swing.JTextField();
        bt_excluiremail = new javax.swing.JButton();
        bt_addemail = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tab_fone = new javax.swing.JTable();
        text_fone = new javax.swing.JTextField();
        bt_excluirfone = new javax.swing.JButton();
        bt_addfone = new javax.swing.JButton();
        tex_sobrenome = new javax.swing.JTextField();
        tex_nome = new javax.swing.JTextField();
        bt_cancelAlt = new javax.swing.JButton();
        bt_gravAlt = new javax.swing.JButton();
        bt_gravNovo = new javax.swing.JButton();
        bt_cancelNovo = new javax.swing.JButton();
        box_email = new javax.swing.JComboBox<>();
        box_fone = new javax.swing.JComboBox<>();
        lb_nome = new javax.swing.JLabel();
        lb_sobrenome = new javax.swing.JLabel();
        lb_img = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        tab_email.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Email", "Tipo", "cod"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tab_email);
        if (tab_email.getColumnModel().getColumnCount() > 0) {
            tab_email.getColumnModel().getColumn(2).setMinWidth(0);
            tab_email.getColumnModel().getColumn(2).setPreferredWidth(0);
            tab_email.getColumnModel().getColumn(2).setMaxWidth(0);
        }

        bt_excluiremail.setText("-");
        bt_excluiremail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_excluiremailActionPerformed(evt);
            }
        });

        bt_addemail.setText("+");
        bt_addemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_addemailActionPerformed(evt);
            }
        });

        tab_fone.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Fone", "Tipo", "cod"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tab_fone);
        if (tab_fone.getColumnModel().getColumnCount() > 0) {
            tab_fone.getColumnModel().getColumn(2).setMinWidth(0);
            tab_fone.getColumnModel().getColumn(2).setPreferredWidth(0);
            tab_fone.getColumnModel().getColumn(2).setMaxWidth(0);
        }

        bt_excluirfone.setText("-");
        bt_excluirfone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_excluirfoneActionPerformed(evt);
            }
        });

        bt_addfone.setText("+");
        bt_addfone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_addfoneActionPerformed(evt);
            }
        });

        tex_nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tex_nomeActionPerformed(evt);
            }
        });

        bt_cancelAlt.setText("cancelar");
        bt_cancelAlt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_cancelAltActionPerformed(evt);
            }
        });

        bt_gravAlt.setText("Gravar alterações");
        bt_gravAlt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_gravAltActionPerformed(evt);
            }
        });

        bt_gravNovo.setText("Gravar");
        bt_gravNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_gravNovoActionPerformed(evt);
            }
        });

        bt_cancelNovo.setText("Cancelar");
        bt_cancelNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_cancelNovoActionPerformed(evt);
            }
        });

        box_email.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { }));

        box_fone.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { }));

        lb_nome.setText("Nome:");

        lb_sobrenome.setText("Sobrenome:");

        lb_img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/telas/logoooo.png"))); // NOI18N

        jLabel1.setText("Telefone");

        jLabel2.setText("Email :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(text_email, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(box_email, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)
                        .addComponent(bt_addemail)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt_excluiremail))
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(lb_img)
                        .addGap(75, 75, 75)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(lb_nome)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tex_nome))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(lb_sobrenome)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tex_sobrenome))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(bt_gravNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(bt_cancelNovo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(bt_gravAlt, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(bt_cancelAlt, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(text_fone, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(box_fone, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bt_addfone)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bt_excluirfone)))))
                .addGap(10, 10, 10))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 10, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bt_cancelNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bt_gravNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tex_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lb_nome))
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tex_sobrenome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lb_sobrenome)))
                    .addComponent(lb_img, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_excluirfone)
                    .addComponent(bt_addfone)
                    .addComponent(text_fone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(box_fone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(text_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(bt_excluiremail)
                        .addComponent(bt_addemail)
                        .addComponent(box_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_cancelAlt, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_gravAlt, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tex_nomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tex_nomeActionPerformed

    }//GEN-LAST:event_tex_nomeActionPerformed

    private void bt_cancelNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_cancelNovoActionPerformed
        dispose();
    }//GEN-LAST:event_bt_cancelNovoActionPerformed

    private void bt_cancelAltActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_cancelAltActionPerformed
        dispose();
    }//GEN-LAST:event_bt_cancelAltActionPerformed

    private void bt_addfoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_addfoneActionPerformed
        DefaultTableModel tab = (DefaultTableModel) tab_fone.getModel();
        if (!"".equals(text_fone.getText().trim())) {
            System.out.println(box_fone.getSelectedIndex());
            tab.addRow(new String[]{text_fone.getText().trim(), (String) box_fone.getSelectedItem(), Integer.toString(box_fone.getSelectedIndex() + 1)});
            text_fone.setText("");
        }

    }//GEN-LAST:event_bt_addfoneActionPerformed

    private void bt_addemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_addemailActionPerformed
        DefaultTableModel tab = (DefaultTableModel) tab_email.getModel();
        
        
        if (!"".equals(text_email.getText().trim())) {
            if(!Util.validEmail(text_email.getText())){
               JOptionPane.showMessageDialog(null, "Este email não é valido ! "); 
            } else {
                tab.addRow(new String[]{text_email.getText().trim(), (String) box_email.getSelectedItem(), Integer.toString(box_email.getSelectedIndex() + 1)});
                text_email.setText("");
            }
        }
    }//GEN-LAST:event_bt_addemailActionPerformed

    private void bt_excluirfoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_excluirfoneActionPerformed
        if(tab_fone.getSelectedRow()== -1){
            return;
        }
        tab_fone.getSelectedRow();
        DefaultTableModel tab = (DefaultTableModel) tab_fone.getModel();
        tab.removeRow(tab_fone.getSelectedRow());
    }//GEN-LAST:event_bt_excluirfoneActionPerformed

    private void bt_excluiremailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_excluiremailActionPerformed
          if(tab_email.getSelectedRow()== -1){
            return;
        }
        tab_email.getSelectedRow();
        DefaultTableModel tab = (DefaultTableModel) tab_email.getModel();
        tab.removeRow(tab_email.getSelectedRow());
    }//GEN-LAST:event_bt_excluiremailActionPerformed

    private void bt_gravAltActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_gravAltActionPerformed
        if ("".equals(tex_nome.getText().trim()) || "".equals(tex_sobrenome.getText().trim())) {
            JOptionPane.showMessageDialog(null, "Nome e/ou sobrenome nao pode estar vazio.");
            return;
        }
        
        try {
            contatoAtual.setNome(tex_nome.getText());
            contatoAtual.setSobrenome(tex_sobrenome.getText());
            contatoAtual.setEmails(novosEmails());
            contatoAtual.setFones(novosFones());
            Consultas.alteraContato(contatoAtual);
            JOptionPane.showMessageDialog(null, "Sucesso");
            dispose();
        } catch (SQLException ex) {
            Logger.getLogger(TelaCadastro.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_bt_gravAltActionPerformed

    private void bt_gravNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_gravNovoActionPerformed
        Contato contato = new Contato();
        if ("".equals(tex_nome.getText().trim()) || "".equals(tex_sobrenome.getText().trim())) {
            JOptionPane.showMessageDialog(null, "Nome e/ou Nao pode estar vazio");
            return;
        }

        DefaultTableModel tabfone = (DefaultTableModel) tab_fone.getModel();
        List<Fone> fones = new ArrayList<Fone>(0);
        for (int linha = 0; linha < tabfone.getRowCount(); linha++) {
            TipoFone tipo = new TipoFone();
            //       tabfone.getValueAt(linha, 2);
            tipo.setCod(Integer.parseInt((String) tabfone.getValueAt(linha, 2)));
            String numero = (String) tabfone.getValueAt(linha, 0);
            fones.add(new Fone(numero, tipo));
        }

        DefaultTableModel tabemail = (DefaultTableModel) tab_email.getModel();
        List<Email> emails = new ArrayList<Email>(0);
        for (int linha = 0; linha < tabemail.getRowCount(); linha++) {
            TipoEmail tipo = new TipoEmail();
            tipo.setCod(Integer.parseInt((String) tabemail.getValueAt(linha, 2)));
            String emai = (String) tabemail.getValueAt(linha, 0);
            emails.add(new Email(emai, tipo));
        }

        contato.setNome(tex_nome.getText());
        contato.setSobrenome(tex_sobrenome.getText());
        contato.setFones(fones);
        contato.setEmails(emails);

        try {
            Consultas.insereContato(contato);

            JOptionPane.showMessageDialog(null, "sucesso");
           // TelaPrincipal.contatosNaTabela();
        } catch (Exception ex) {
            Logger.getLogger(TelaCadastro.class.getName()).log(Level.SEVERE, null, ex);
        }

        dispose();
    }//GEN-LAST:event_bt_gravNovoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> box_email;
    private javax.swing.JComboBox<String> box_fone;
    private javax.swing.JButton bt_addemail;
    private javax.swing.JButton bt_addfone;
    private javax.swing.JButton bt_cancelAlt;
    private javax.swing.JButton bt_cancelNovo;
    private javax.swing.JButton bt_excluiremail;
    private javax.swing.JButton bt_excluirfone;
    private javax.swing.JButton bt_gravAlt;
    private javax.swing.JButton bt_gravNovo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lb_img;
    private javax.swing.JLabel lb_nome;
    private javax.swing.JLabel lb_sobrenome;
    private javax.swing.JTable tab_email;
    private javax.swing.JTable tab_fone;
    private javax.swing.JTextField tex_nome;
    private javax.swing.JTextField tex_sobrenome;
    private javax.swing.JTextField text_email;
    private javax.swing.JTextField text_fone;
    // End of variables declaration//GEN-END:variables
}
